<eclipse>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 ECLIPSE SPECIAL OPTIONS CHECKED OUT:                                    
 lgr                                                                     
</message>
<message date="1/1/2000" time="0.00000000000000">
 CHECKING FOR LICENSES                                                   
</message>
<message date="1/1/2000" time="0.00000000000000">
 ECLIPSE LICENSE CHECKED OUT                                             
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE GRID SECTION IS                      
      25219 KBYTES                                                       
</message>
<message date="1/1/2000" time="0.00000000000000">
 NEITHER OLDTRAN,OLDTRANR NOR NEWTRAN SPECIFIED                          
 BLOCK CENTRE TRANSMISSIBILITIES TO BE CALCULATED                        
 USING  OLDTRAN                                                          
</message>
<comment date="1/1/2000" time="0.00000000000000">
 NO NON-NEIGHBOUR CONNECTIONS IN GLOBAL GRID                             
</comment>
<message date="1/1/2000" time="0.00000000000000">
 NUMBER OF ACTIVE GLOBAL CELLS IS 441                                    
 NUMBER OF ACTIVE  LOCAL CELLS IS 0                                      
  TOTAL NUMBER OF ACTIVE CELLS IS 441                                    
</message>
<message date="1/1/2000" time="0.00000000000000">
 THE MEMORY REQUIRED TO PROCESS THE SOLUTION SECTION IS                  
       7270 KBYTES                                                       
</message>
<message date="1/1/2000" time="0.00000000000000">
    63868 CHARACTER VARIABLES USED                                       
</message>
<warning date="1/1/2000" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL INJ                             
 HAS BEEN DEFAULTED. THE DEFAULT VALUE IS  100000.   PSIA                
</warning>
<message date="1/1/2000" time="0.00000000000000">
 OPENING WELL INJ      AT TIME      0.00   DAYS                          
 CONTROLLED BY WATER RATE                                                
</message>
<warning date="1/1/2000" time="0.00000000000000">
 THE BOTTOM HOLE PRESSURE LIMIT FOR WELL PRD                             
 HAS BEEN DEFAULTED.  THE DEFAULT VALUE IS                               
     14.7   PSIA                                                         
</warning>
<message date="1/1/2000" time="0.00000000000000">
 OPENING WELL PRD      AT TIME      0.00   DAYS                          
 CONTROLLED BY LIQUID RATE                                               
</message>
<message date="1/1/2000" time="0.00000000000000">
 RESTART FILE WRITTEN   REPORT     0                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  WATER AND GAS PHASE PRESSURES                          
</message>
<message date="1/1/2000" time="0.00000000000000">
 ******************************************                              
 * WELL PRD      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME      0.00   DAYS  .          *                              
 ******************************************                              
</message>
<message date="2/1/2000" time="1.55078120231596">
 ******************************************                              
 * WELL INJ      HAS CHANGED TO           *                              
 * CONTROL BY BOTTOM HOLE PRESSURE        *                              
 * FROM TIME      1.55   DAYS  .          *                              
 ******************************************                              
</message>
<message date="10/4/2000" time="100.00000000000000">
 RESTART FILE WRITTEN   REPORT     1                                     
 RESTART INCLUDES INTERBLOCK FLOWS                                       
                  WATER AND GAS PHASE PRESSURES                          
</message>
</eclipse>
